### ISSUE TITLE
 php-xapi/client 0.6.x-dev requires php-http/httplug ^1.0 

### ISSUE THREAD

**Issue by djoudi** [php-xapi/client#34]
php-xapi/client 0.6.x-dev requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2, v1.0.0-alpha3, v1.0.0-beta, v1.1.0] but these conflict with your requirements or minimum-stability.

 Installation request for php-xapi/client ^0.6.0@dev -> satisfiable by php-xapi/client[0.6.x-dev].

**Comment by coder-sukanta** [comment]
I am also faching the same issue.

Problem 1
    - Installation request for php-xapi/client ^0.5.0 -> satisfiable by php-xapi/client[v0.5.0].
    - php-xapi/client v0.5.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2, v1.0.0-alpha3, v1.0.0-beta, v1.1.0] but these conflict with your requirements or minimum-stability.

**Comment by xabbuh** [comment]
Can you show your `composer.json` file?

**Comment by coder-sukanta** [comment]
Here is my composer.json file 

{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.8.*",
        "php-http/guzzle6-adapter": "^2.0",
        "php-http/httplug": "^2.0",
        "vlucas/phpdotenv": "^3.3"
    },
    "require-dev": {
        "fzaninotto/faker": "^1.4",
        "phpunit/phpunit": "^7.0",
        "mockery/mockery": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by xabbuh** [comment]
Oh I see, you are already using HTTPlug 2 which means that there is a conflict. I will take a look later to add support for HTTPlug 2 to this client. Thank you for reporting.

**Comment by coder-sukanta** [comment]
@xabbuh Can please confirm me how much time it will take to provide support for HTTPlug 2??

**Comment by xabbuh** [comment]
I have just tagged the 0.6.0 release. Can you confirm that this release fixes your issue?
